# Generated by Django 4.2.11 on 2025-10-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameID', models.CharField(max_length=50, unique=True)),
                ('HomeTeam', models.CharField(max_length=75)),
                ('AwayTeam', models.CharField(max_length=75)),
                ('HomeScore', models.IntegerField()),
                ('AwayScore', models.IntegerField()),
                ('Week', models.IntegerField()),
            ],
        ),
    ]
