# Generated by Django 4.2.11 on 2025-10-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0002_game_date_alter_game_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='GameID',
            field=models.CharField(max_length=50),
        ),
    ]
