# Generated by Django 4.2.11 on 2025-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0003_alter_game_gameid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldIDs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameID', models.CharField(max_length=50)),
                ('week', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=15)),
            ],
        ),
    ]
