# Generated by Django 4.2.11 on 2025-10-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0004_holdids'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='holdids',
            name='date',
            field=models.DateField(),
        ),
    ]
