# Generated by Django 5.2.7 on 2025-10-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0005_game_updated_at_alter_holdids_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Week',
            field=models.CharField(blank=True, default='missing', max_length=15, null=True),
        ),
    ]
