# Generated by Django 5.2.7 on 2025-10-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0006_alter_game_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameID', models.CharField(max_length=50)),
                ('data', models.JSONField()),
            ],
        ),
    ]
