# Generated by Django 5.2.7 on 2025-10-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0007_gamedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='data',
            field=models.TextField(),
        ),
    ]
