# Generated by Django 5.2.7 on 2025-10-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0008_alter_gamedata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='GameID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='holdids',
            name='GameID',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
