# Generated by Django 5.2.7 on 2025-11-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0010_team_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
