# Generated by Django 4.2.11 on 2025-11-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0011_profile_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbr',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='logo_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
