# Generated by Django 4.2.11 on 2025-11-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0012_team_abbr_team_logo_path_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='TeamID',
            field=models.AutoField(db_column='TeamID', primary_key=True, serialize=False),
        ),
    ]
