# Generated by Django 5.2.7 on 2025-11-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0013_remove_team_id_alter_team_teamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_team',
            field=models.JSONField(default=[]),
        ),
    ]
