# Generated by Django 5.2.7 on 2025-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0014_profile_favorite_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_team',
            field=models.JSONField(default=['Test']),
        ),
    ]
