# Generated by Django 5.2.7 on 2025-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0015_alter_profile_favorite_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_team',
            field=models.JSONField(default={'fav_teams': []}),
        ),
    ]
