# Generated by Django 5.2.7 on 2025-11-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0016_alter_profile_favorite_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='new',
        ),
        migrations.AddField(
            model_name='profile',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
    ]
