# Generated by Django 5.2.7 on 2025-11-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0017_remove_profile_new_profile_login_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
