# Generated by Django 5.2.7 on 2025-11-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0018_profile_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='new',
        ),
    ]
