# Generated by Django 5.2.7 on 2025-12-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportstracker_app', '0019_remove_profile_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
